# example netlify.toml
[build]
  command = "cd packages/frontend && yarn build"
  functions = "lambdas"
  publish = "packages/frontend/public/"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/api/npm-registry/*"
  to = "https://registry.npmjs.org/:splat"
  status = 200

[[headers]]
   for = "/api/npm-api/*"
   [headers.values]
      Access-Control-Allow-Origin = "*"

[[redirects]]
  from = "/api/npm-api/*"
  to = "https://api.npmjs.org/:splat"
  status = 200

[[headers]]
   for = "/api/npm-registry/*"
   [headers.values]
      Access-Control-Allow-Origin = "*"
